### ISSUE TITLE
avoidStrutsUnlessFullscreen

### ISSUE THREAD

**Issue by ptrxyz** [Nadrieril/xmonad-config#1]
I found your code for the "avoidStrutsUnlessFullscreen" thingy and I wonder if there is a way to add "noBorders" to it. If an application is on fullscreen, I'd like to not only have it ignore struts but also hide the borders. I am not a Haskell programmer, so could you please help me with that?

**Comment by Nadrieril** [comment]
I believe it should not be too hard. I'll try looking at the code of the noBorders layout when I find time. Maybe I'll even find a more general approach to the problem.

**Comment by Nadrieril** [comment]
Here you go: https://github.com/Nadrieril/xmonad-config/commit/788311883db7f940194d729499e0428fbdc1e72f

Also, my new layout combinator `ifFullscreen` should be straightforward to use.

**Comment by ptrxyz** [comment]
Great! Thank you a lot!
